elasticsearch:
  url: 'http://download.elasticsearch.org/elasticsearch/elasticsearch'
  deb:
    package: 'elasticsearch-0.90.10.deb'
    service: 'elasticsearch'
    dependencies:
      - 'openjdk-6-jre'
      - 'openjdk-6-jdk'
  plugin: '/usr/share/elasticsearch/bin/plugin'
  config: '/etc/elasticsearch/elasticsearch.yml'

  tmp: '/tmp'

paramedic:
  index: '/usr/share/elasticsearch/plugins/paramedic/_site/index.html'
  name: 'karmi/elasticsearch-paramedic'
